package saaq.client;

import java.util.List;
import java.util.ArrayList;
import java.util.Properties;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import saaq.ejb.SAAQServiceRemote;
import saaq.entity.Car;
import saaq.entity.Owner;

public class SAAQClient extends javax.swing.JFrame {

    SAAQServiceRemote service;
    DefaultListModel<Car> carListModel;
    DefaultListModel<Owner> ownerListModel;
    ArrayList<Car> carlist;
    ArrayList<Owner> ownerlist;
//    String car;

    public SAAQClient() {
        try {
            Properties props = new Properties();
            // props.load(new FileInputStream("jndi.properties"));
            props.setProperty("java.naming.factory.initial", "com.sun.enterprise.naming.SerialInitContextFactory");
            InitialContext ctx = new InitialContext(props);
            service = (SAAQServiceRemote) ctx.lookup(SAAQServiceRemote.class.getName());
            //
            carListModel = new DefaultListModel<Car>();
            ownerListModel = new DefaultListModel<Owner>();
            initComponents();
            updateCarList();
            updateOwnerList();
//            balance = service.addOwner(owner);
//            jlCar.setText(String.valueOf(balance));
        } catch (NamingException ex) {
            // ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error connectiong to Glassfish");
            throw new RuntimeException("Error connecting to Glassfish", ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfOwner = new javax.swing.JTextField();
        btAddOwner = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfCar = new javax.swing.JTextField();
        btAddCar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlOwner = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlCar = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Owner:");

        tfOwner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfOwnerActionPerformed(evt);
            }
        });

        btAddOwner.setText("Add");
        btAddOwner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddOwnerActionPerformed(evt);
            }
        });

        jLabel2.setText("Car:");

        tfCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCarActionPerformed(evt);
            }
        });

        btAddCar.setText("Add");
        btAddCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddCarActionPerformed(evt);
            }
        });

        jlOwner.setModel(ownerListModel);
        jlOwner.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jlOwner);

        jlCar.setModel(carListModel);
        jlCar.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jlCar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfOwner, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btAddOwner))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfCar)
                        .addGap(18, 18, 18)
                        .addComponent(btAddCar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAddOwner)
                    .addComponent(jLabel2)
                    .addComponent(tfCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAddCar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddOwnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddOwnerActionPerformed
        try {
            String name = tfOwner.getText();
            Owner o = new Owner();
            o.setName(name);
            service.addOwner(o);
            updateOwnerList();
            tfOwner.setText("");
        } catch (RuntimeException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btAddOwnerActionPerformed

    private void btAddCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddCarActionPerformed
        try {
            String makeModel = tfCar.getText();
            if(makeModel.isEmpty()){
                JOptionPane.showMessageDialog(this, "Car must not be empty");
                return;
            }
            Owner selectedOwner = (Owner) jlOwner.getSelectedValue();
            if(jlOwner.isSelectionEmpty()){
                JOptionPane.showMessageDialog(this, "Please select an owner");
                return;
            }
            
            Car car = new Car();
            car.setMakeModel(tfCar.getText());
            car.setOwner(selectedOwner);
            service.addCar(car);

            updateCarList();
            tfCar.setText("");
        } catch (RuntimeException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btAddCarActionPerformed

    private void tfOwnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfOwnerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfOwnerActionPerformed

    private void tfCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCarActionPerformed

    List<Owner> ownerList = new ArrayList<>();
    void updateOwnerList() {
        ownerList = service.getOwnerList();
        ownerListModel.clear();
        for (Owner o: ownerList) {
            ownerListModel.addElement(o);
        }
    }

    List<Car> carList = new ArrayList<>();
    void updateCarList() {
        carList = service.getCarList();
        carListModel.clear();
        for (Car c : carList) {
            carListModel.addElement(c);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SAAQClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SAAQClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SAAQClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SAAQClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SAAQClient().setVisible(true);
            }
        });
    }

      

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddCar;
    private javax.swing.JButton btAddOwner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<Car> jlCar;
    private javax.swing.JList<Owner> jlOwner;
    private javax.swing.JTextField tfCar;
    private javax.swing.JTextField tfOwner;
    // End of variables declaration//GEN-END:variables
}
