package ui;

import entity.Course;
import entity.Student;
import java.text.ParseException;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.PersistenceException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class FancyRegUI extends javax.swing.JFrame {

    EntityManagerFactory emf;
    EntityManager em;

    public FancyRegUI() {
        try {
            emf = javax.persistence.Persistence.createEntityManagerFactory("FancyRegJPAPU");
            em = emf.createEntityManager();
            initComponents();
            updateStudentList();
            updateCourseList();
        } catch (PersistenceException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error connecting to database");
            System.exit(1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        btAddName = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlStudents = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        btRegister = new javax.swing.JButton();
        btUnregister = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlRegistrations = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        tfCourse = new javax.swing.JTextField();
        btAddCourse = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlCources = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name:");

        btAddName.setText("Add");
        btAddName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddNameActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jlStudents);

        jLabel2.setText("Registrations:");

        btRegister.setText("Register");
        btRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegisterActionPerformed(evt);
            }
        });

        btUnregister.setText("Unregister");
        btUnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUnregisterActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jlRegistrations);

        jLabel3.setText("Course:");

        btAddCourse.setText("Add");
        btAddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddCourseActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(jlCources);

        jLabel4.setText("Students");

        jLabel5.setText("Cources");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)))
                        .addComponent(btAddName)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btUnregister))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(tfCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btAddCourse))
                            .addComponent(jScrollPane3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAddName)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(tfCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAddCourse))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btRegister)
                            .addComponent(btUnregister)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddNameActionPerformed
        String name = tfName.getText();
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Name must not be empty");
            return;
        }
        addStudent(name);
        updateStudentList();
        tfName.setText("");
    }//GEN-LAST:event_btAddNameActionPerformed

    private void btAddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddCourseActionPerformed
        String subject = tfCourse.getText();
        if (subject.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Subject must not be empty");
            return;
        }
        addCourse(subject);
        updateCourseList();
        tfCourse.setText("");
    }//GEN-LAST:event_btAddCourseActionPerformed

    private void btRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegisterActionPerformed
//        try {
//            String name = tfName.getText();
//            String dateString = tfDate.getText();
//            if (name.isEmpty()) {
//                JOptionPane.showMessageDialog(this, "Name must not be empty");
//                return;
//            }
//            SimpleDateFormat format = new SimpleDateFormat("yyyy/MM/dd");
//            Date dob = format.parse(dateString);
//            addPerson(name, dob);
//            updatePeopleList();
//            tfName.setText("");
//            tfDate.setText("");
//        } catch (ParseException ex) {
//            JOptionPane.showMessageDialog(this, "Date must be in YYYY/MM/DD format");
//        }
    }//GEN-LAST:event_btRegisterActionPerformed

    private void btUnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUnregisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btUnregisterActionPerformed

    void addStudent(String name) {
        Student s = new Student();
        s.setName(name);
        //
        em.getTransaction().begin();
        try {
            em.persist(s);
            em.getTransaction().commit();
        } catch (Exception ex) {
            ex.printStackTrace();
            em.getTransaction().rollback();
            JOptionPane.showMessageDialog(this, "Error adding student record");
        }
    }

    void updateStudentList() {
        List<Student> list = em.createQuery("SELECT s FROM Student s").getResultList();
        DefaultListModel model = new DefaultListModel();
        for (Student s : list) {
            model.addElement(s.getName());
        }
        jlStudents.setModel(model);
        System.out.println("LIST: " + list);
        // TODO: add to JTable
    }

    void addCourse(String subject) {
        Course c = new Course();
        c.setSubject(subject);
        //
        em.getTransaction().begin();
        try {
            em.persist(c);
            em.getTransaction().commit();
        } catch (Exception ex) {
            ex.printStackTrace();
            em.getTransaction().rollback();
            JOptionPane.showMessageDialog(this, "Error adding course record");
        }
    }

    void updateCourseList() {
        List<Course> list = em.createQuery("SELECT c FROM Course c").getResultList();
        DefaultListModel model = new DefaultListModel();
        for (Course c : list) {
            model.addElement(c.getSubject());
        }
        jlCources.setModel(model);
        System.out.println("LIST: " + list);
        // TODO: add to JTable
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FancyRegUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FancyRegUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FancyRegUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FancyRegUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FancyRegUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddCourse;
    private javax.swing.JButton btAddName;
    private javax.swing.JButton btRegister;
    private javax.swing.JButton btUnregister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> jlCources;
    private javax.swing.JList<String> jlRegistrations;
    private javax.swing.JList<String> jlStudents;
    private javax.swing.JTextField tfCourse;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
